### ISSUE TITLE
dsh-sql-0.2.0.0 fails "cabal test" stage

### ISSUE THREAD

**Issue by peti** [ulricha/dsh-sql#1]
Citing from http://hydra.cryp.to/build/913586/log/raw:

```
Running 1 test suites...
Test suite sqltests: RUNNING...
sqltests: usage: sqltests <odbc dbname>
Test suite sqltests: FAIL
```

Maybe it's not a good idea to register a test suite in the "test" stage that the "test" stage cannot run? As a result, our automatic builds of this package fail in NixOS.

**Comment by ulricha** [comment]
Indeed, that should've been just an executable.

Thanks for the report, fixed in dc87cbd18c78ba7368f16629b3ba292fbde4c443.

**Comment by peti** [comment]
Will you release a new version?

**Comment by ulricha** [comment]
Sure, I did. See https://github.com/ulricha/dsh-sql/releases/tag/v0.2.0.1 which is on Hackage.
